export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE'
export const AUTH_START_WORK = 'AUTH_START_WORK'
export const AUTH_STOP_WORK = 'AUTH_STOP_WORK'

export const SESSION_SET_URL_ROOT = 'SESSION_SET_URL_ROOT'
export const SESSION_LOGIN = 'SESSION_LOGIN'
export const SESSION_LOGOUT = 'SESSION_LOGOUT'
export const SESSION_LOAD_STATE_FROM_STORAGE = 'SESSION_LOAD_STATE_FROM_STORAGE'
export const SESSION_SET_LOADING = 'SESSION_SET_LOADING'

export const USER_LOAD_INFO = 'USER_LOAD_INFO'
export const USER_CLEAR = 'USER_CLEAR'

export const TEAM_LOAD_INFO = 'TEAM_LOAD_INFO'
export const TEAM_LOAD_USERS = 'TEAM_LOAD_USERS'
export const TEAM_LOAD_VAULT = 'TEAM_LOAD_VAULT'

export const SECRET_SET = 'SECRET_SET'
export const SECRET_SET_BULK = 'SECRET_SET_BULK'
export const SECRET_UNSET = 'SECRET_UNSET'
export const SECRET_CLEAR_ALL = 'SECRET_CLEAR_ALL'
export const SECRET_SET_LOADING = 'SECRET_SET_LOADING'
