export const SESSION_LOGIN = 'SESSION_LOGIN'
export const SESSION_LOGOUT = 'SESSION_LOGOUT'
export const SESSION_EXISTS = 'SESSION_EXISTS'

export const USER_LOAD_INFO = 'USER_LOAD_INFO'
export const USER_CLEAR = 'USER_CLEAR'

export const TEAM_LOAD_INFO = 'TEAM_LOAD_INFO'
export const TEAM_LOAD_USERS = 'TEAM_LOAD_USERS'
export const TEAM_LOAD_VAULT = 'TEAM_LOAD_VAULT'

export const SECRET_SET = 'SECRET_SET'
export const SECRET_SET_BULK = 'SECRET_SET_BULK'
export const SECRET_UNSET = 'SECRET_UNSET'
export const SECRET_CLEAR_ALL = 'SECRET_CLEAR_ALL'
export const SECRET_SET_LOADING = 'SECRET_SET_LOADING'
