export const SESSION_SET_URL_ROOT = 'SESSION_SET_URL_ROOT';
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const SESSION_LOAD_STATE_FROM_STORAGE = 'SESSION_LOAD_STATE_FROM_STORAGE';
export const SESSION_SET_LOADING = 'SESSION_SET_LOADING';
export const SESSION_START_WORK = 'SESSION_START_WORK';
export const SESSION_STOP_WORK = 'SESSION_STOP_WORK';
